/* eslint-disable no-empty */

Ti.App.addEventListener('uncaughtException', error => {
	console.error(`ðŸ›‘ Unhandled Exception -- error:`);
	console.error(error);
	try {
		logger.error('uncaughtException', error);
	} catch (ex) {}
});

// NOTE: event name is camelCase as per node convention
process.on('unhandledRejection', (error, promise) => {
	// See Promise.onPossiblyUnhandledRejection for parameter documentation
	console.error(`ðŸ“Œ  you are here â†’ process.on('unhandledRejection')`);
	console.error(`ðŸ›‘  error: ${JSON.stringify(error, null, 2)}`);
	console.error(`ðŸ›‘  promise: ${JSON.stringify(promise, null, 2)}`);
	console.error(error);
	try {
		logger.error('unhandledRejection', error);
	} catch (ex) {}

});

// NOTE: event name is camelCase as per node convention
process.on('rejectionHandled', promise => {
	// See Promise.onUnhandledRejectionHandled for parameter documentation

	console.error(`ðŸ“Œ  you are here â†’ process.on('rejectionHandled')`);
	console.error(`ðŸ›‘  promise: ${JSON.stringify(promise, null, 2)}`);
});

const unhandledPromises = [];
Promise.onPossiblyUnhandledRejection((reason, promise) => {
	console.error(`ðŸ“Œ  you are here â†’ Promise.onPossiblyUnhandledRejection`);
	console.error(`ðŸ›‘  reason: ${JSON.stringify(reason, null, 2)}`);
	console.error(`ðŸ›‘  promise: ${JSON.stringify(promise, null, 2)}`);
	unhandledPromises.push(promise);
	// Update some debugger UI
});

Promise.onUnhandledRejectionHandled(promise => {
	console.error(`ðŸ“Œ  you are here â†’ Promise.onUnhandledRejectionHandled`);
	console.error(`ðŸ›‘  promise: ${JSON.stringify(promise, null, 2)}`);
	const index = unhandledPromises.indexOf(promise);
	unhandledPromises.splice(index, 1);
	// Update the debugger UI
});
