/* eslint-disable no-empty */
const logger = require(`@geek/logger`);


Ti.App.addEventListener(`uncaughtException`, error => {
	console.error(`ðŸ›‘ Unhandled Exception -- error:`);
	console.error(error);
	try {
		logger.error(`uncaughtException`, error);
		turbo.tracker.error(error);
		Alloy.Globals.aca.logHandledException(error);
	} catch (ex) {}
});


if (global.IS_DEV) {

	// global.onunhandledrejection = e => console.log('unhandled', e.reason, e.promise);
	global.onunhandledrejection = e => {

		console.error(`ðŸ›‘ Unhandled Promise Rejection -- error:`);
		console.error(e.reason);
		try {
			logger.error(`onunhandledrejection`, e.reason);
			turbo.tracker.error(e.reason);
			Alloy.Globals.aca.logHandledException(e.reason);
		} catch (ex) {}
	};


	Ti.App.addEventListener(`onunhandledrejection`, error => {
		console.error(`ðŸ›‘ Unhandled Rejection -- error:`);
		console.error(error);
		try {
			logger.error(`onunhandledrejection`, error);
			turbo.tracker.error(error);
			Alloy.Globals.aca.logHandledException(error);
		} catch (ex) {}
	});

	// NOTE: event name is camelCase as per node convention
	process.on(`unhandledRejection`, (error, promise) => {
	// See Promise.onPossiblyUnhandledRejection for parameter documentation
		console.error(`ðŸ“Œ  you are here â†’ process.on('unhandledRejection')`);
		console.error(`ðŸ›‘  error: ${JSON.stringify(error, null, 2)}`);
		console.error(`ðŸ›‘  promise: ${JSON.stringify(promise, null, 2)}`);
		console.error(error);
		try {
			logger.error(`unhandledRejection`, error);
			turbo.tracker.error(error);
			Alloy.Globals.aca.logHandledException(error);
		} catch (ex) {}

	});

	// NOTE: event name is camelCase as per node convention
	process.on(`rejectionHandled`, promise => {
	// See Promise.onUnhandledRejectionHandled for parameter documentation

		console.error(`ðŸ“Œ  you are here â†’ process.on('rejectionHandled')`);
		console.error(`ðŸ›‘  promise: ${JSON.stringify(promise, null, 2)}`);
		console.error(promise);
	});

	const unhandledPromises = [];
	Promise.onPossiblyUnhandledRejection((reason, promise) => {
		console.error(`ðŸ“Œ  you are here â†’ Promise.onPossiblyUnhandledRejection`);
		console.error(`ðŸ›‘  reason: ${JSON.stringify(reason, null, 2)}`);
		console.error(`ðŸ›‘  promise: ${JSON.stringify(promise, null, 2)}`);
		console.error(promise);
		unhandledPromises.push(promise);
	// Update some debugger UI
	});

	Promise.onUnhandledRejectionHandled(promise => {
		console.error(`ðŸ“Œ  you are here â†’ Promise.onUnhandledRejectionHandled`);
		console.error(`ðŸ›‘  promise: ${JSON.stringify(promise, null, 2)}`);
		console.error(promise);
		const index = unhandledPromises.indexOf(promise);
		unhandledPromises.splice(index, 1);
	// Update the debugger UI
	});


}
